### ISSUE TITLE
Add the ability to type in the numerical value of the LED intensity

### ISSUE THREAD

**Issue by dysonsphere-startmail** [Aharoni-Lab/Miniscope-DAQ-QT-Software#10]
It would be helpful to be able to type in the LED intensity as an alternate option to using the slider.
Would it also be able to add the ability to set the LED intensity in the config file, so that the intensity could be coded to be consistent between sessions on the same mouse?

**Comment by daharoni** [comment]
Hi @dysonsphere-startmail,
We will consider adding an optional text box for numerical enter of certain control parameters but I am not completely sure I want to add this yet.

You should be able to set the LED intensity in the user config file already:
![image](https://user-images.githubusercontent.com/16613835/86557504-300e2400-bf0b-11ea-9f5d-283a64f18784.png)
