### ISSUE TITLE
Without the exe file located in the main directory

### ISSUE THREAD

**Issue by neugun** [Aharoni-Lab/Miniscope-DAQ-QT-Software#12]
Hi,  I visited the releases page of this repository and download the newest version of the software. When i unzip the compiled package, i  didn't found the .exe file located in the main directory. Am I miss some key steps or didn't install any software? 
Thanks!

**Comment by daharoni** [comment]
Hello, I just checked the .zip file and the .exe file is located there. See picture below for reference.
![image](https://user-images.githubusercontent.com/16613835/88145689-ad928f00-cbaf-11ea-837f-2e28dcfd267e.png)

**Comment by neugun** [comment]
Thanks for the help! I realized I downloaded the source code. Now it is ok!
