### ISSUE TITLE
LED not updating for v3 miniscope

### ISSUE THREAD

**Issue by wmau** [Aharoni-Lab/Miniscope-DAQ-QT-Software#18]
I'm using a v3 scope with v1.01 acquisition software (native Windows 10) and the LED does not seem to turn on when I connect it to the software. It's also affected by changing the LED power slider. But it does work with the old non-QT software. Any clue what's happening?

**Comment by daharoni** [comment]
Hey Will,
Just to clarify, when you say it is also affected by changing the LED power slider, do you mean that the LED does or does not turn on and change intensity?

**Comment by wmau** [comment]
Oh sorry, two corrections: 
The LED _does_ turn on when I connect it to the software, but moving the slider _does not_ change the LED power.

**Comment by wmau** [comment]
The gain slider also does not seem to do anything.

**Comment by wmau** [comment]
Sorry one more correction -- launching the new acquisition software by itself does not turn on the LED. The LED just retains the brightness set by the old acquisition software after closing it.

**Comment by wmau** [comment]
The DAQ I'm using was ordered from LabMaker in Jan and came preprogrammed. Is there a way to check its firmware?

**Comment by daharoni** [comment]
You will need to reprogram it with the newest firmware then.

**Comment by wmau** [comment]
Gotcha. I'll reprogram it and follow up if it still doesn't work. Thanks Daniel!

**Comment by daharoni** [comment]
Glad this solved the issue. 

I have only done minimal testing with this new software and the V3 so if you do run into any other issues please post them here as I might have missed something.
