### ISSUE TITLE
Recording 20 FPS in v3 

### ISSUE THREAD

**Issue by przemyslawj** [Aharoni-Lab/Miniscope-DAQ-QT-Software#24]
Hello,

Option to record with 20 FPS in miniscope v3 was removed. This was the default option I used for recordings and I wonder if the 20 FPS could be brought back? I believe it was removed in commit 2f17c7bef13b9268dccee4a2fe232f7533235d7d

Best,
Prez

**Comment by daharoni** [comment]
Thanks Prez. I must have accidently changed this in the deviceConfigs/miniscopes.json file at some point. I will correct this in a future release. For now, you can open up the miniscopes.json file in any text editor and change the "frameRate:" entry for the V3 Miniscope to be:

```
"frameRate": {
                "displaySpinBoxValues":["10FPS", "15FPS", "20FPS", "30FPS", "60FPS"],
                "displayTextValues": [10, 15, 20, 30, 60],
                "outputValues":[49153250,43057902,57016641, 6160929, 6094881],
                "outputValues2":[1720,1220,800,1000,500],
                "startValue": "20FPS",
}
```

This should give you back the missing frame rates for the V3.

**Comment by daharoni** [comment]
Just added this to 8d50eb2cb2b45e3bfbc9beacf454261c431ac087 in the 'dev' branch. Next full release will include the correction.

Thanks again for posting this issue.
