### ISSUE TITLE
Hardcoded dataDirectory values in all userConfigs/*.json files

### ISSUE THREAD

**Issue by DenisPolygalov** [Aharoni-Lab/Miniscope-DAQ-QT-Software#25]
All userConfigs/*.json files contain hard-coded paths such as 
**C:/Users/dbaha/Documents/Data** and **C:/Users/DBAharoni/Documents/Data**
These paths contain Windows 10 user name unique to developers PCs 
and therfore are invalid for most of the users.
Moreover Windows 10 does not allow directory creation in C:\Users easily
because this is well, inappropriate.

**Comment by fnsangiul** [comment]
You can change the path to your own by editing the json file

**Comment by DenisPolygalov** [comment]
Yes, **I** can. I can edit the JSON file or rewrite this whole thing from scratch, but my intent for reporting this bug is to help other less experienced users to deal with bugs in this software. Why I think this is a bug: simply because this behavior of the software goes against standards related to data storage and provoke other users to keep and spread this practice. The correct way of dealing with this is to use QStandardPaths Class: https://doc.qt.io/qt-5/qstandardpaths.html
Feel free to close if you think it is appropriate to do so.

**Comment by drojf** [comment]
Note that the person who replied to you isn't a contributor, so perhaps they were just suggesting a temporary fix for the issue.

**Comment by daharoni** [comment]
Hi @DenisPolygalov, Thanks for pointing this out. Haha, I probably do a lot of things in programming that are in the ballpark of being "inappropriate". I will add this to my to do list for things to update in the next software release. Hopefully I will have time to work on it over winter break.

**Comment by daharoni** [comment]
We will now include only 1 user configuration example JSON file with releases. This file will have absolute paths removed along with notes/comments explaining how users should construct and add their own paths.
