### ISSUE TITLE
I cannot turn off the LED before recording.

### ISSUE THREAD

**Issue by WuKaiibin** [Aharoni-Lab/Miniscope-DAQ-QT-Software#26]
I am now using v1.02, everything goes fine but I can not turn off the LED even I turn the intensity sliders to zero. How to turn off the LED in the GUI?

**Comment by daharoni** [comment]
@WuKaiibin, Are you using the new Version 4 Miniscope (V4) or are you using the previous generation of Miniscope (V3)? The V3 does not have the ability to turn its excitation LED completely off.

**Comment by daharoni** [comment]
Haven't heard back from @WuKaiibin. I am assuming this is due to the V3. Will close this issue until further clarified.
