### ISSUE TITLE
Framerate from config file isn't used 

### ISSUE THREAD

**Issue by hahnjohannes** [Aharoni-Lab/Miniscope-DAQ-QT-Software#28]
No matter what I set in the config file, the starting framerate always seems to be 30 Hz for the miniscope. 

The top of the imaging window shows ~30 FPS and that's also seems to be the real rate but the menu shows what is given in the confi. When I change it in the menu with the +/- button I move from the one set in the config file, not from 30.
 
This is the case on three different PCs I tried

**Comment by daharoni** [comment]
Thanks for the post. I will fix this in the upcoming release which should be posted by the end of the year.

**Comment by daharoni** [comment]
This should now be fixed in e1fc68f849780b2caf8fe673d1f40fec5a710534  commit. It will be included in the upcoming new release of the software.
