### ISSUE TITLE
V4 Miniscope retrieve frame failed

### ISSUE THREAD

**Issue by Grand-Laborer** [Aharoni-Lab/Miniscope-DAQ-QT-Software#31]
![miniscope V4](https://user-images.githubusercontent.com/66052703/103654329-b1b93a00-4fa0-11eb-9061-fbf5dd2f8563.PNG)

We can't receive V4 miniscope signals, as shown above. The warning shows "V4 Miniscope retrieve frame failed".  Is there anything wrong with the DAQ board or the user configutation?

Thanks!

**Comment by daharoni** [comment]
Have you tried changing the "deviceID" in the user config file?

**Comment by Grand-Laborer** [comment]
> Have you tried changing the "deviceID" in the user config file?

Yes. We've tried 0, 1, 2, which didn't work.

**Comment by Richardo-M-Yang** [comment]
Hi， when I use miniscope_V4 I got the same problem with you, May I ask you how to deal with it? I had already try for a month, but it still doesn't work.

**Comment by Grand-Laborer** [comment]
> Hi， when I use miniscope_V4 I got the same problem with you, May I ask you how to deal with it? I had already try for a month, but it still doesn't work.

I don't quite remember. The problem might be solved by updating the firmware of the DAQ box.
