### ISSUE TITLE
Errors reading json metaData files in Python Pandas

### ISSUE THREAD

**Issue by dysonsphere-startmail** [Aharoni-Lab/Miniscope-DAQ-QT-Software#34]
I am attempting to convert the json files to dataframes in Python using Pandas in order to read them into my databases as tables.
For pandas to read the json as a table it must be formatted with "[ ]" around the items so as to be read as a list.
Example:
```
{
    "compression": ["GREY"],
    "deviceDirectory": ["/home/m3coordinator/Videos/Dr_Miniscope/Codec_Tests/testGREY/2020_07_14/14_57_38/Miniscope"],
    "deviceID": [2],
    "deviceName": ["Miniscope"],
    "deviceType": ["Miniscope_V3"],
    "frameRate": ["30FPS"],
    "framesPerFile": [1000],
    "gain": ["Low"],
    "led0": [30]
}
```
Is it possible to have the json files write out like this by default, or is there another reason to not include the "[ ]"?
Thanks

**Comment by daharoni** [comment]
This would add one additional step to reading in and working with all json values in QT. Basically we would need to add in a conversion .toArray()[0] for every read of json values throughout the Miniscope software which would be quite a pain to implement. 

This seems somewhat strange on Pandas end as the json file standard does not require the values of keys to be lists and allows them to be bools, ints, doubles, strings, object, or arrays/lists. Would you be able to use
`import json`
instead? I am pretty sure the json module in python would work with our json format.

**Comment by dysonsphere-startmail** [comment]
Ah, OK. I was not familiar with the json module in python.
I am able to read in the json metaData with:
```
>>> f = open('/home/kdys/Data/Testing/Codec_Tests/testGREY/2020_07_14/14_57_38/Miniscope/metaData.json', "r")
>>> data = json.loads(f.read())
```
Not sure how to covert this to a table, but will look into it.
Thanks!
