### ISSUE TITLE
Behaviour video window is not full size

### ISSUE THREAD

**Issue by lalde** [Aharoni-Lab/Miniscope-DAQ-QT-Software#38]
Hi miniscope team, 

I am using the v4 scope with the 1.02 software version and I have the following issue: the behaviour stream doesn't show all of the frame, and the window is very small (see screenshot attached)
The issue also happens when using the 1.0 version. I also tried with version 1.1 but the software crashes as soon as the behaviour steam comes up.
We've had no issue when using the same DAQ, scope and config file on a different rig with version 1.0 so I am a bit confused. 

Best,
Lucie 
![image](https://user-images.githubusercontent.com/41382274/110219753-51237c00-7ec1-11eb-8d44-00adcffca3dd.png)

**Comment by daharoni** [comment]
Hi @lalde,
I haven't run across this issue before but I have a few ideas what is causing it and how to fix it. 

- Can you do a quick recording and tell me the horizontal and vertical resolution of the saved behavior camera .avi file?
- Can you also try changing the "deviceType" for the camer to just "WebCam"?

**Comment by lalde** [comment]
Hi @daharoni,

Thanks for the reply! I've changed the deviceType to "Webcam" and the window is a tad bigger, but still crops most of the frame, and this with all software versions (1.0, 1.02 and 1.1)
When trying to do a recording the whole software crashes, so I cannot check the dimensions of the .avi file 
![Capture](https://user-images.githubusercontent.com/41382274/110309671-ed549c80-8001-11eb-98e2-9198e527fa88.PNG)

**Comment by lalde** [comment]
Hi again!

I tried a few more things today, it is still not working but perhaps it can be helpful for debugging: 
- If I only have the scope plugged in, I can record without any problem 
- If I resize the ROI within the behaviour window, then the software doesn't crash and I can record. The dimensions of the .avi file are the following: 88 width by 102 height

Best,
Lucie

**Comment by daharoni** [comment]
Hi,

- Definitely the crashing issue was from the ROI defined in the user config file being larger than the actual resolution of the video stream. I thought I had something in the code to double check this and limit the ROI to the max size of the video resolution but I guess not. I will add this in a future release. For now, just completely remove the ROI section in your user config file if you don't need it.
- The issue with the behavior camera window being too small is the software currently is expecting the resolution of the behavior camera to be different than it actually is. Can you delete the ROI section from your user config file and record for a few seconds again and then let me know the resolution of the saved behavior video? Thanks!

**Comment by lalde** [comment]
I've just tried and now the resolution is 640 x 480 - it's getting there! But it is still smaller than the config file values, so we still can't see all of the arena

**Comment by lalde** [comment]
Hi Daniel, 
I changed the dimensions of "webcam" in the videoDevices.json file so it matches the deimensions in the userConfig file, and now it's working well :)

**Comment by daharoni** [comment]
Thanks for the update @lalde. I think I have a fix for this so this issue doesn't occur when using the standard "Webcam" device in the user config. I have added it to my to do list and will try to include it in our next release.
