### ISSUE TITLE
Why is recorded video fixed 60 fps?

### ISSUE THREAD

**Issue by m11o** [Aharoni-Lab/Miniscope-DAQ-QT-Software#46]
When recording video by miniscope v4 and miniscope-DAQ, recorded video is fixed at 60 fps.
If `frameRate` is 20 in a user configuration file, I think the recorded video is wanted to save with the same fps.
However, it is currently saved with 60 fps. 
So, when it is displayed by a video player (VLC etc...), it is played faster than real.

Would you please tell me why the recorded video is fixed at 60 fps?
Thanks!

ref: 
https://docs.opencv.org/4.1.0/dd/d9e/classcv_1_1VideoWriter.html#a0901c353cd5ea05bba455317dab81130
https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/4999be0ce0e2cf7d8da4c0bed6ffe0b679cd90ea/source/datasaver.cpp#L202-L204
https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/4999be0ce0e2cf7d8da4c0bed6ffe0b679cd90ea/source/datasaver.cpp#L207-L209

**Comment by masahito1997** [comment]
Great!
Thank you for your replying.

**Comment by daharoni** [comment]
The user configuration file allows you to set the default frame rate the Miniscope will initially stream at. You can then further adjust the FPS using the controls within the software. 

In other words, users can adjust the real Miniscope FPS (10, 15, 20, 25, 30FPS) using the user config and in software controls but the recorded .AVI files will always have a "playback" FPS of 60. This playback FPS is completely independent of what the Miniscope was actually running at.
