### ISSUE TITLE
The .exe file can't be excused by python or other external programme?

### ISSUE THREAD

**Issue by Aaronhuang-778** [Aharoni-Lab/Miniscope-DAQ-QT-Software#54]
I try to use qt, pyqt  and python(os,subprocess) but the WebCam page can't be opened
and the error is : My V4 Miniscope has error: 1; My WebCam has error: 1

**Comment by daharoni** [comment]
I don't quite follow. The included .exe in the release is meant to run on its own without the need for qt, pyqt, or python.
