### ISSUE TITLE
Add the ability to change/add metadata labels in the user config file.

### ISSUE THREAD

**Issue by dysonsphere-startmail** [Aharoni-Lab/Miniscope-DAQ-QT-Software#6]
It would be great to have ability to change and add metadata labels in the user config file.

This would enable the researcher to change the metadata labels to the ones they are currently using in their database, and to add additional directories that match the standardized data structure for their analysis pipeline.

For example, in the current build (0.163):
I tried changing "animalName" to "animal_ID" and it ignores it in the directory structure and shows `"animalName" : "" `
in the metaData.json file.
I tried adding new metadata to the list in the userConfig.json and the directory structure and metaData.jason ignored them as well.

**Comment by daharoni** [comment]
Hey @dysonsphere-startmail, this is a great suggestion. Adding this feature is very straightforward and will be included in the next incremental release (hopefully sometime next week).

**Comment by daharoni** [comment]
This feature is now added to the master branch of this repo (de78aea6f2e74152eedcc0d361c77e6fc8e0c926). 

You can now add custom keys into the directoryStructure array in the user config file. You then have to actually have that name/value pair declared within the JSON file. 

I have a few more things to add to the source code and then will make a new release. Thanks again for the suggestion.
