### ISSUE TITLE
minicam with daq v3.3

### ISSUE THREAD

**Issue by blaingvt** [Aharoni-Lab/Miniscope-DAQ-QT-Software#63]
I recently acquired minicams, miniscope daq v3.3, and miniscopes. 

I am having trouble getting the Miniscope Daq QT Software to successfully load the Minicam-Mono-XGA. 

I select the behaviorCams JSON file and run then image 2 below pops up. However, when I press record nothing happens, the timer starts but no frames are visible. Is there a link or suggestion on how to proceed? Thank you very much, sorry for the rudimentary issue. 

![image](https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/assets/64107313/82de6630-ce44-43a4-b63f-9f4d095947f9)
![image](https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/assets/64107313/cc7b13c9-fafc-4c1e-a9fa-8e370f250597)

**Comment by sneakers-the-rat** [comment]
@daharoni does the DAQ have a debug mode or log to check or something?

**Comment by fnsangiul** [comment]
Hello @blaingvt. For reference, the user configuration for the MiniCAM looks like this: 

![image](https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/assets/45947951/4564a396-b18f-4793-8163-bad37bce74d1)

I'm attaching the userconfig that I use to test several MiniCAMs connected to my computer. If you only have one connected then only one window will open. Hope this helps
[UserConfigExample-miniCAM_test.json](https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/files/13197114/UserConfigExample-miniCAM_test.json)

**Comment by blaingvt** [comment]
thank you very much. this got me right.

**Comment by fnsangiul** [comment]
Cool, glad it worked. You can remove the other Minicams that are not connected and add Miniscopes for example.
