### ISSUE TITLE
Can the miniscope brightness go below 1?

### ISSUE THREAD

**Issue by sneakers-the-rat** [Aharoni-Lab/Miniscope-DAQ-QT-Software#68]
@hsw [asks](https://neuromatch.social/@aheadofthenerve/111841522311058878):

> so um anyone know if the @MiniscopeTeam brightness can go below 1? I tried setting it to 0.5 in the config but unsure it actually worked. (yes gain is already down... I could increase sampling rate then downsample later but that is annoying to have to do for one animal only :-p)

Here's an ~hour of me reading code trying to compensate for the lack of docs to get whoever is going to handle this potentially embarassing bug started:

From what I can tell this is set by the `led0` property in a config `.json` file - https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/deviceConfigs/userConfigProps.json#L244-L247

there are [several places](https://github.com/search?q=repo%3AAharoni-Lab%2FMiniscope-DAQ-QT-Software+fromJson&type=code) that json files appear to be read in, but it seems like the primary way this happens is this set of functions that are called when the user configuration path is set: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/backend.cpp#L615-L621

and are stored in an object `ucMiniscopes`: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/backend.cpp#L790

which are used to create `new Miniscope` objects here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/backend.cpp#L932

but then it also looks like the device type key in the user config loads some standard set of params here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/videodevice.cpp#L42 so not really sure what value gets initialized, 

although here it does appear that the settings are initially populated in the gui sliders from the user config: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/videodevice.cpp#L373-L380

but it's not clear to me that that signal/slot is connected when the signal is emitted. probably is, but not sure.

---

I see that the GUI connects the LED slider here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/Miniscope_V4.qml#L213

which is handled here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/videodevice.cpp#L575

so `m_lastLED0Value` seems to carry the LED value: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/videodevice.cpp#L577

and the following lines there seem to send the command to the miniscope over I2C, but that's where the code starts to elude me... there is some object `m_controlSendCommand`. 

That gets populated here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/videodevice.cpp#L387

from here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/deviceConfigs/miniscopes.json#L58-L75

so theoretically it should be set like any other param. 

I am not sure what happens here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/videodevice.cpp#L595-L624

but it doesn't look like there is any check for success when setting parameters, so it's unclear if that works.

I'm not sure if there is any sort of range validation - there is a note in the source about an upper limit (should not be set above 70), but i am not sure about decreasing it below 0. Sliders are notoriously bad UI objects for precise control, so whenever I present them I always ensure that they are coupled with a textbox that can set the value numerically. If there is some kind of range validation in the GUI components, that would override the value set in the user config. it looks like the LED might be fixed to [integer steps](https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/deviceConfigs/miniscopes.json#L268), so in that case the answer would be no, it can't be set below 1. It's not clear to me whether that's from a firmware limitation or if that's an arbitrary GUI thing. The values are cast `toDouble` so that makes me think the firmware is capable of parsing floats, but the firmware is a whole different beast that I know at a very cursory level. Eg maybe [this is](https://github.com/Aharoni-Lab/Miniscope-v4/blob/81de4bb894e4debfcc07da5a57b8a0a9bf0b377b/Miniscope-v4-MCU-Firmware/Atmel/Miniscope-v4-MCU/Miniscope-v4-MCU/main.c#L93) where the LED value is set, i don't really know. 

Unfortunately, this software lacks docs, tests, and a build system, so I can't point you to where you might find out more, validate any of this behavior, or fix it, so... whomp whomp

**Comment by hsw28** [comment]
thanks for looking at this!! I was setting it to 0<value<1 in the param file and it wasn't erroring, but it would automatically have it as 1 on the slider when I started up the program.

**Comment by hsw28** [comment]
Also you tagged the wrong account above, I was later to the game and had to put the 28 onto hsw :(

**Comment by jonnew** [comment]
Whats up @hsw28! Been a while :). At the end of the long Rube Goldberg machine, there is a digital potentiometer which controls the current passing though the LED to determine its brightness. This has 256 taps and therefore there are 256 discrete current/brightness levels. I'm not sure how the 1-100 setting on the QT software is transformed into these 256 levels. I would assume via some reasonable rounding that probably maps 1 -> lowest current step. On the [bonsai package](https://github.com/open-ephys/Bonsai.Miniscope/tree/master), they are brought out directly and so you have access to all of them, in case this is helpful.

``` csharp
        [Range(0, 255)]
        [Editor(DesignTypes.SliderEditor, typeof(UITypeEditor))]
        [Description("LED brightness.")]
        public double LEDBrightness { get; set; } = 0;
```

Edit: I have not verified that the firmware running on the camera actually directly writes these values to the pot, but it would take work _not_ to do that, so I assume it does.

**Comment by hsw28** [comment]
Hey @jonnew :) ! Thanks for the info! Depending if they mapped 0 or 1 to 256 maybe I have a little wiggle room, if I can access the lower values.
Any chance you'll be at cosyne this year?

**Comment by fnsangiul** [comment]
Solution addressed [here](https://github.com/Aharoni-Lab/Miniscope-v4/issues/37). None of the solutions explained above are correct for this issue.

**Comment by sneakers-the-rat** [comment]
so I found where the display values are mapped to the I2C values here: https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/0fecb97cca82c694b1b40dde03cd759e23ad3224/source/VideoSliderControl.qml#L73

so for a value of 1, the value that gets written over I2C is 
`(1 * -2.55) + 255 = 252.45` so you actually do have a bit of headroom on the software side. 

So unless we want to go with "you need to resolder a resistor onto your miniscope" as the accepted answer to this solution, this should stay open, since both fixing that and changing the exposure as suggested [here](https://github.com/Aharoni-Lab/Miniscope-v4/issues/37#issuecomment-1918092438) are certainly preferable outcomes that should be added to docs. but whatever

**Comment by fnsangiul** [comment]
It depends on what the user needs. I personally would prefer a lower irradiance by limiting the current of the LED as it would reduce photobleaching over time. Also, the digital potentiometer ([datasheet here](https://www.ti.com/lit/ds/symlink/tpl0102-100.pdf)) only takes integers.

**Comment by raymondwjang** [comment]
How exactly would lowering the brightness via hardware setting vs the software setting make a difference in photo bleaching?

Also isn't Jonny suggesting we could throttle it up to 255?

**Comment by fnsangiul** [comment]
You can't change the brightness of the LED via software. Please refer to the LED driver (LTC3218) datasheet: 
![image](https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/assets/45947951/43d9d9b2-5dde-4320-aed8-f4ca5cb6c9c3)

My suggestion for lowering the LED intensity via hardware is based on this graph. The software option of reducing the exposure doesn't change the amount of irradiance that reaches the brain. It only captures less light in the image sensor. That's why the only sensible option to reduce photobleaching is to reduce the LED intensity.

**Comment by sneakers-the-rat** [comment]
Presumably the firmware truncates the remainder on the float, thats the part of the code I dont rly get (and why it would be dope to have tests to validate). Still that means there are 2 more clicks to be had of lowered brightness that would be desirable to be able to test before resoldering the scope, since OP says they dont want to have to modify this for one animal. The luminance isnt decreased, but the PWM time is, right? Trying to stay responsive to the issue at hand, and OP hasnt specified a problem with bleaching (but I could be wrong?) 

Since we are trying to EOL this software, I would suggest @hsw28  try bonsai as @jonnew suggests, which can write the values directly, and see if that is enough, then since presumably they know about photobleaching, try the gain thing, and then if that still isnt enough then resistor change.

Ideally we would have docs with a FAQ section that describes the tradeoffs @fnsangiul describes between lowering intensity, exposure, and resoldering the resistor as a last resort. Typically if the resolution to an issue is docs, you leave it open until the docs get written. In the meantime, these two issues are an imperfect replacement for that. (Idc really about the closedness of this issue, im just happy we are raising them instead of debugging individually over email lol)

**Comment by fnsangiul** [comment]
@sneakers-the-rat I don't know how to make more clear that dealing with the potentiometer won't enable an intensity lower than the minimum. You can try if you want but you won't get any useful result. The two possible solutions for this issue are

1. Changing the Rset resistor to 100k based on the graph I posted above sourced directly from the LTC3218 datasheet
2. Change the exposure time by setting it on the user configuration files of the Miniscope QT software.

Option one makes the overall Miniscope excitation dimmer, which is preferred if you want to minimize photobleaching at the expense of making the Miniscope not usable on dimmer mice. Option two doesn't change at all the excitation power of the Miniscope, it just makes it less efficient by lowering the exposure time of the image sensor. On my end I'll post solution two and close this issue.

**Comment by raymondwjang** [comment]
Oh, is the led brightness fixed at a hardware level? As in you can't change it once the Miniscope is deployed?

Nonetheless, I think Jonny's point then is that you could lower the exposure time into the pixels via software and thus keep them from saturating. Am I correct? @sneakers-the-rat

**Comment by sneakers-the-rat** [comment]
Loud and clear on the fact that the LED has a fixed intensity,  but the brightness setting does control PWM correct?

What im saying is that the "1" value does not translate to the minimum that the PWM controller can do - setting to 1 sends a value of 252, so the firmware can accept 253 and 254 before turning off at 255, but the software cant send those values because of how the 1-100 range is mapped to 0-255. Aka there is a software bug here orthogonal to the luminance of the LED.

Not sure where the tone is coming from, all im saying is that it would probably be good to try bonsai (which can set the minimum PWM value) and exposure settings first before resoldering the component, since the first two options might meet the needs here and allow the scope to be used with the other animals. I get what youre saying and am not even disagreeing that obvi changing the resistor would decrease intensity and is one way of addressing the issue.

**Comment by daharoni** [comment]
Alright, let's take this discussion offline for the time being as it is beginning to feel like this thread is becoming counter productive.

@sneakers-the-rat, @fnsangiul, @RaymondWJang, and I need to have a discussion in person and then we will respond. 

Thanks for raising this issue @hsw28.
