### ISSUE TITLE
Triggering the TTL on does not turn off the LED.

### ISSUE THREAD

**Issue by dysonsphere-startmail** [Aharoni-Lab/Miniscope-DAQ-QT-Software#7]
The experimenter needs to manually set the LED back to zero once the recording stops.
It would be great if the Trigger could turn the LED off as was the case with the old software.

**Comment by daharoni** [comment]
We had this implemented in the previous Miniscope software but I haven't figured out an elegant way of implementing this in the new software structure. I will definitely work on this.

**Comment by daharoni** [comment]
This feature has now been added (70c1a70398b069b694e294b7c18ffe5e65a21276). It should work with V4 and V3 Miniscopes as well as any future devices with an excitation LED. It will be included in the upcoming release later in the week.
