### ISSUE TITLE
There is no indication that a recording has stopped from the trigger other than the countdown timer stopping

### ISSUE THREAD

**Issue by dysonsphere-startmail** [Aharoni-Lab/Miniscope-DAQ-QT-Software#8]
It would be nice to have a timestamp that confirms that the experiment has ended after the ttl trigger.

**Comment by daharoni** [comment]
Agreed. I added some text that displays for trigger high, trigger low, and recording stopped now (f8e8afa5577614fbd5256f99f3bb4224b4ed171b)
