### ISSUE TITLE
When recording via TTL trigger, there is no manual way to stop the recording except by closing the software.

### ISSUE THREAD

**Issue by dysonsphere-startmail** [Aharoni-Lab/Miniscope-DAQ-QT-Software#9]
It would be great if there was the option to stop the recording the way one can with the manual start option.

**Comment by daharoni** [comment]
I will think about this. My thought initially was I wanted to disable all manual control of stopping and starting recording if triggering was enabled. I definitely see the usefulness of being able to still manually stop recording.

**Comment by daharoni** [comment]
This has now been added (70c1a70398b069b694e294b7c18ffe5e65a21276). The text of the Start and Stop buttons change to let the user know that external triggering is enabled. If user or external tries to stop or start recording when it is not possible a warning shows up. This will be included in the release later in the week.
